<a href="https://colab.research.google.com/github/ayush5/-CS69002_9A_18CS60R26/blob/master/MLP_Tutorial_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Movie Review Sentiment Analysis

## Import Header files

In [0]:
import torch
import pandas as pd
import numpy as np

In [2]:
print('Welcome to Computing Lab 2. The current PyTorch version is ', torch.__version__)

Welcome to Computing Lab 2. The current PyTorch version is  1.0.1.post2


## Load the dataset and visualize


There are 3 ways to do this:

(a)  From Github (Files < 25MB)

The easiest way to upload a CSV file is from your GitHub repository. Click on the dataset in your repository, then click on View Raw. Copy the link to the raw dataset and store it as a string variable called url in Colab as shown below (a cleaner method but it’s not necessary). The last step is to load the url into Pandas read_csv to get the dataframe.


```
url = 'copied_raw_GH_link'
df1 = pd.read_csv(url)
# Dataset is now stored in a Pandas Dataframe

```

---


(b) From a local drive

To upload from your local drive, start with the following code:

```
from google.colab import files
uploaded = files.upload()
```

It will prompt you to select a file. Click on “Choose Files” then select and upload the file. Wait for the file to be 100% uploaded. You should see the name of the file once Colab has uploaded it.

Finally, type in the following code to import it into a dataframe (make sure the filename matches the name of the uploaded file).
```
import io
df2 = pd.read_csv(io.BytesIO(uploaded['Filename.csv']))
# Dataset is now stored in a Pandas Dataframe
```

---


(c) From Google drive

This the most complicated of the three methods. Follow this [link](https://medium.freecodecamp.org/how-to-transfer-large-files-to-google-colab-and-remote-jupyter-notebooks-26ca252892fa) to learn more.

In [0]:
url = 'https://raw.githubusercontent.com/binny-mathew/IITKGP_CS69002_Spring_2019/master/Dataset/Train_20K.csv'
df_train = pd.read_csv(url, sep='\t')
url="https://raw.githubusercontent.com/binny-mathew/IITKGP_CS69002_Spring_2019/master/Dataset/Test_5K.csv"
df_test= pd.read_csv(url, sep="\t")

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
type(uploaded), uploaded.keys(), type(uploaded['check.csv'])

In [0]:
import io
df = pd.read_csv(io.StringIO(uploaded['check.csv'].decode('utf-8')), sep='\t')
df.head()

## Pandas

[Pandas](https://pandas.pydata.org/) is a high-performance, easy-to-use data structure and data analytics tool for Python.

Tutorials:

*   [Link 1](https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html)
*   [Link 2](https://www.tutorialspoint.com/python_pandas)
*   [Link 3](https://www.dataquest.io/blog/pandas-python-tutorial/)



In [5]:
print('Number of Negative movie reviews', len(df[df['label']==0]))
print('Number of Positive movie reviews', len(df[df['label']==1]))

NameError: ignored

## Data pre-processing
The first step when building a neural network model is getting your data into the proper form to feed into the network. We'll need to encode each word with an integer. We'll also want to clean it up a bit.

You can use any type of pre-processing that you see fit, based on the task. For the tutorial, i will show just one pre-processing step: **lowercasing**.

In [4]:
text_reviews = df_train['text'].astype(str).tolist()
text_labels = df_train['label'].astype(int)

text_reviews = [x.lower() for x in text_reviews]
text_reviews[0], text_labels[0]

('john waters has given us a genuinely enjoyable film. this certainly isn\'t without its shocking waters-esque moments, but it is tamer than his older culty stuff, such as "pink flamingoes". "pecker" harkens back to john\'s early mainstream stage in that it reminds the viewer of the same kind of humor that was evident in "polyester". overall, a really fun comedy with some great moments!',
 1)

In [5]:
len(text_reviews)

17999

In [6]:
text_reviews = df_test['text'].astype(str).tolist()
text_labels = df_test['label'].astype(int)

text_reviews = [x.lower() for x in text_reviews]
text_reviews[0], text_labels[0]

("as always this is an inaccurate picture of the homeless. tv told a lot of lies about panhandlers in the early 1990s and made everyone look bad, and claimed we all made over $100 a day when $20-40 a day was much closer to reality. when someone drove by where i held up a sign offering to work, and offered me work, i actually went and took the work if i was physically able.and if i would been offered the $100,000 id damned sure invested in in apt prepaid for at least 2 years, and kept most in the bank and still left myself $10-20000 for nl $1-2 and $2-5 cash games at the casinos. i usually always win and could win decent if i just had a bankroll. instead i win about $1000 a month is all playing in always minimum buying in due to not wanting to risk losing it all. i was only homeless cause i didn't wanna risk spending all my money and going broke, sometimes i had over $1000-2000 in my sock while i slept outside. anyone wanting to talk contact sevencard2003 on yahoo messenger.i admit i wa

In [8]:
len(test_reviews)

NameError: ignored

## Creating Bag Of Word (BOW) representation of sentences.

In [0]:
def generate_word_ids(dataset):
  word_to_ix = {}
  for sent in dataset:
      for word in sent.split():
          if word not in word_to_ix:
              word_to_ix[word] = len(word_to_ix)
  return word_to_ix

In [8]:
generate_word_ids(['welcome to computing lab 2'])

{'2': 4, 'computing': 2, 'lab': 3, 'to': 1, 'welcome': 0}

In [9]:
train_text= df_train['text'].astype(str).tolist()
train_label=df_train['label'].astype(int)
test_text=df_test['text'].astype(str).tolist()
test_label=df_test['label'].astype(int)
print (train_text[0])

John Waters has given us a genuinely enjoyable film. This certainly isn't without its shocking Waters-esque moments, but it is tamer than his older culty stuff, such as "Pink Flamingoes". "Pecker" harkens back to John's early mainstream stage in that it reminds the viewer of the same kind of humor that was evident in "Polyester". Overall, a really fun comedy with some great moments!


In [0]:
from string import punctuation

In [11]:
train_reviews_cleaned = []
for i in range(len(train_text)):
    train_reviews_cleaned.append(''.join([c.lower() for c in train_text[i] if c not in punctuation]))
train_text=train_reviews_cleaned
print (train_text[0])

john waters has given us a genuinely enjoyable film this certainly isnt without its shocking watersesque moments but it is tamer than his older culty stuff such as pink flamingoes pecker harkens back to johns early mainstream stage in that it reminds the viewer of the same kind of humor that was evident in polyester overall a really fun comedy with some great moments


In [12]:
test_reviews_cleaned = []
for i in range(len(test_text)):
    test_reviews_cleaned.append(''.join([c.lower() for c in test_text[i] if c not in punctuation]))
test_text=test_reviews_cleaned
print (test_text[0])

as always this is an inaccurate picture of the homeless tv told a lot of lies about panhandlers in the early 1990s and made everyone look bad and claimed we all made over 100 a day when 2040 a day was much closer to reality when someone drove by where i held up a sign offering to work and offered me work i actually went and took the work if i was physically ableand if i would been offered the 100000 id damned sure invested in in apt prepaid for at least 2 years and kept most in the bank and still left myself 1020000 for nl 12 and 25 cash games at the casinos i usually always win and could win decent if i just had a bankroll instead i win about 1000 a month is all playing in always minimum buying in due to not wanting to risk losing it all i was only homeless cause i didnt wanna risk spending all my money and going broke sometimes i had over 10002000 in my sock while i slept outside anyone wanting to talk contact sevencard2003 on yahoo messengeri admit i was different than most homeless

In [0]:
#data = [("me gusta comer en la cafeteria", "SPANISH"),
        ("Give it to me", "ENGLISH"),
        ("No creo que sea una buena idea", "SPANISH"),
        ("No it is not a good idea to get lost at sea", "ENGLISH")]

#test_data = [("Yo creo que si", "SPANISH"),
             ("it is lost on me", "ENGLISH")]

In [13]:
word_to_ix = generate_word_ids(train_text+test_text)

VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2
print(VOCAB_SIZE)

116102


In [0]:
from collections import Counter
def vocabulary_reduction(reviews,labels,min_freq,polarity_cut_off):
    
    pos_count = Counter()
    neg_count = Counter()
    tot_count = Counter()

    for i in range(len(reviews)):
        for word in reviews[i].split():
            tot_count[word]+=1
            if labels[i] == 1:
                pos_count[word]+=1
            else:
                neg_count[word]+=1    
    
    #Identify words with frequency greater than min_freq
    vocab_freq = []
    print(min_freq)
    for word in tot_count.keys():
        if tot_count[word]>min_freq:
            vocab_freq.append(word) 
    
    
    #Use polarity to reduce vocab
    pos_neg_ratio = Counter()
    vocab_pos_neg = (set(pos_count.keys())).intersection(set(neg_count.keys()))
    for word in vocab_pos_neg:
        if tot_count[word]>100:
            ratio = pos_count[word]/float(neg_count[word]+1)
            if ratio>1:
                pos_neg_ratio[word] = np.log(ratio)
            else:
                pos_neg_ratio[word] = -np.log(1/(ratio+0.01)) 
    
    mean_ratio = np.mean(list(pos_neg_ratio.values()))
    
    vocab_polarity = []
    for word in pos_neg_ratio.keys():
        if (pos_neg_ratio[word]<(mean_ratio-polarity_cut_off)) or (pos_neg_ratio[word]>(mean_ratio+polarity_cut_off)):
            vocab_polarity.append(word)
     
    vocab_rm_polarity = set(pos_neg_ratio.keys()).difference(vocab_polarity)
    vocab_reduced = (set(vocab_freq)).difference(set(vocab_rm_polarity))
 
    reviews_cleaned = []
    
    for review in reviews:
        review_temp = [word for word in review.split() if word in vocab_reduced]
        reviews_cleaned.append(' '.join(review_temp))
    
    return reviews_cleaned

In [56]:
train_text=vocabulary_reduction(train_text,train_label,5,0.1)

5


In [52]:
word_to_ix = generate_word_ids(train_text)

VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2
print(VOCAB_SIZE)

15847


In [54]:
print(word_to_ix)

{'john': 0, 'waters': 1, 'has': 2, 'given': 3, 'us': 4, 'genuinely': 5, 'enjoyable': 6, 'this': 7, 'certainly': 8, 'isnt': 9, 'moments': 10, 'tamer': 11, 'than': 12, 'his': 13, 'older': 14, 'stuff': 15, 'as': 16, 'pink': 17, 'pecker': 18, 'johns': 19, 'early': 20, 'mainstream': 21, 'stage': 22, 'reminds': 23, 'viewer': 24, 'same': 25, 'kind': 26, 'humor': 27, 'was': 28, 'evident': 29, 'overall': 30, 'really': 31, 'fun': 32, 'some': 33, 'great': 34, 'seasons': 35, 'series': 36, 'were': 37, 'very': 38, 'and': 39, 'they': 40, 'werent': 41, 'funny': 42, 'had': 43, 'drama': 44, 'element': 45, 'bill': 46, 'mother': 47, 'struggling': 48, 'usual': 49, 'life': 50, 'bit': 51, 'depressing': 52, 'didnt': 53, 'mix': 54, 'well': 55, 'th': 56, 'why': 57, 'dropped': 58, 'soon': 59, 'became': 60, 'funniest': 61, 'bbc': 62, 'have': 63, 'ever': 64, 'made': 65, 'chemistry': 66, 'between': 67, 'bens': 68, 'there': 69, 'always': 70, 'so': 71, 'many': 72, 'brilliant': 73, 'memorable': 74, 'sketches': 75, 'ea

In [17]:
print (train_text[0])

john waters has given us genuinely enjoyable this certainly isnt moments tamer than his older stuff as pink pecker johns early mainstream stage reminds viewer same kind humor was evident overall really fun some great moments


## Intro to PyTorch

In [0]:
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

SEED = 42

torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)

lin = nn.Linear(5,3)
data1 = Variable(torch.randn(10,5)) # create a 10 * 5 matrix of random vars

In [19]:
data1, data1.size()

(tensor([[-0.4974,  0.4396, -0.7581,  1.0783,  0.8008],
         [ 1.6806,  0.3559, -0.6866,  0.6105,  1.3347],
         [-0.2316,  0.0418, -0.2516,  0.8599, -0.3097],
         [-0.3957, -0.2234,  1.7174,  0.3189, -0.4245],
         [ 0.3057, -0.7746,  0.0349,  0.3211, -0.8798],
         [-0.6011, -1.2742,  2.1228, -1.2347, -0.4879],
         [-1.4181,  0.8963,  0.0780,  0.5258,  0.3466],
         [-0.1973, -1.0546,  1.2780,  0.1453,  0.2311],
         [ 0.0087, -0.1423,  0.5750, -0.6417, -2.2064],
         [-0.7508,  2.8140,  0.3598, -0.0898,  0.4584]]), torch.Size([10, 5]))

In [20]:
lin(data1), lin(data1).size()

(tensor([[ 0.3739,  0.1674, -0.1029],
         [ 0.8355,  0.0414,  0.8471],
         [ 0.2831,  0.6893, -0.1183],
         [-0.2887,  1.0737,  0.3888],
         [-0.0317,  0.9654, -0.0386],
         [-1.4234,  0.7988,  0.2472],
         [-0.0414,  0.1357, -0.2777],
         [-0.6189,  0.8737,  0.3820],
         [-0.2207,  0.9984, -0.2671],
         [ 0.6052, -0.4270,  0.2221]], grad_fn=<AddmmBackward>),
 torch.Size([10, 3]))

In [21]:
lin.weight.size()

torch.Size([3, 5])

**BE VERY CAREFUL WITH THE DIMENSIONS**

In [22]:
F.relu(lin(data1))  # Activation Function

tensor([[0.3739, 0.1674, 0.0000],
        [0.8355, 0.0414, 0.8471],
        [0.2831, 0.6893, 0.0000],
        [0.0000, 1.0737, 0.3888],
        [0.0000, 0.9654, 0.0000],
        [0.0000, 0.7988, 0.2472],
        [0.0000, 0.1357, 0.0000],
        [0.0000, 0.8737, 0.3820],
        [0.0000, 0.9984, 0.0000],
        [0.6052, 0.0000, 0.2221]], grad_fn=<ReluBackward0>)

## Model Definition for the BOWClassifier

In [0]:
class BOWClassifier(nn.Module):
  def __init__(self, num_labels, vocab_size):
    super(BOWClassifier, self).__init__()
    self.lin = nn.Linear(vocab_size, 50)
    self.lin2 = nn.Linear(50, num_labels)
    
    
  def forward(self, x):
    z=F.softmax(self.lin(x))
    return F.softmax(self.lin2(z))

##Generate the BOW Vectors

In [0]:
def make_bow_vector(sentence, word_to_ix):
    # create a vector of zeros of vocab size = len(word_to_idx)
    vec = torch.zeros(len(word_to_ix))
    for word in sentence.split():
        if word not in word_to_ix:
            continue
        else:
            vec[word_to_ix[word]]+=1
    return vec.view(1, -1)

def make_target(label, label_to_ix):
    return torch.LongTensor([label_to_ix[label]])


In [0]:
bow = BOWClassifier(NUM_LABELS, VOCAB_SIZE).cuda()

In [26]:
for param in bow.parameters():
    print(param,param.size())

Parameter containing:
tensor([[ 0.0048, -0.0019,  0.0045,  ...,  0.0064,  0.0068,  0.0031],
        [-0.0020, -0.0046, -0.0016,  ...,  0.0055, -0.0068,  0.0046],
        [ 0.0010,  0.0062, -0.0069,  ...,  0.0064, -0.0054, -0.0051],
        ...,
        [ 0.0026, -0.0058, -0.0039,  ...,  0.0062,  0.0051,  0.0033],
        [-0.0005,  0.0071,  0.0022,  ..., -0.0079, -0.0005,  0.0031],
        [-0.0047, -0.0050, -0.0012,  ..., -0.0007,  0.0064,  0.0031]],
       device='cuda:0', requires_grad=True) torch.Size([50, 15848])
Parameter containing:
tensor([-0.0012, -0.0061,  0.0039, -0.0073, -0.0004, -0.0041,  0.0005, -0.0013,
        -0.0037, -0.0021,  0.0025, -0.0035,  0.0013, -0.0009,  0.0076,  0.0053,
        -0.0052, -0.0068,  0.0017,  0.0033,  0.0016,  0.0039,  0.0002, -0.0025,
         0.0063,  0.0079,  0.0049,  0.0017,  0.0041, -0.0071,  0.0019, -0.0039,
        -0.0037,  0.0006,  0.0027, -0.0073,  0.0038, -0.0058,  0.0037,  0.0020,
        -0.0065,  0.0073, -0.0036, -0.0049, -0.0012,  

### Let's check with a sample case how our model is working

In [27]:
sample_data=test_text[0]
sample_label = test_label[0]
bow_vector = torch.autograd.Variable(make_bow_vector(sample_data, word_to_ix))
logprobs = bow(bow_vector)
print()
print(logprobs)

RuntimeError: ignored

In [28]:
label_to_ix = {0: 0, 1: 1}
ix_to_label = {v: k for k, v in label_to_ix.items()}

label_to_ix, ix_to_label

({0: 0, 1: 1}, {0: 0, 1: 1})

In [29]:

for y,instance in enumerate(test_text):
    label=test_label[y]
    bow_vec = Variable(make_bow_vector(instance, word_to_ix)).cuda()
    logprobs = bow(bow_vec)
    print(logprobs)
    pred = np.argmax(logprobs.data.numpy())
    print('prediction: {}'.format(ix_to_label[pred]))
    print('actual: {}'.format(label))


tensor([[0.5034, 0.4966]], device='cuda:0', grad_fn=<SoftmaxBackward>)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


TypeError: ignored

In [0]:
# define a loss function and an optimizer
loss_function = nn.NLLLoss()
opt = torch.optim.SGD(bow.parameters(), lr = 0.1)

In [32]:
# the training loop
for epoch in range(10):
    print(epoch)
    for y,instance in enumerate(train_text):
        # get the training data
        label=train_label[y]
        bow.zero_grad()
        bow_vec = Variable(make_bow_vector(instance, word_to_ix)).cuda()
        label = Variable(make_target(label, label_to_ix)).cuda()
        probs = bow(bow_vec) # forward pass
        probs = probs
        loss = loss_function(probs, label)
        loss.backward()
#        print('CURRENT LOSS: {}'.format(loss.data))
        opt.step()
        


0


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


1
2
3
4
5
6
7
8
9


In [39]:
total_count=0
correct_count=0
print('--- AFTER TRAINING ---')
for y,instance in enumerate(test_text):
    label=test_label[y]
    bow_vec = Variable(make_bow_vector(instance, word_to_ix)).cuda()
    logprobs = bow(bow_vec)
    print(logprobs)
    pred = np.argmax(logprobs.data.cpu().numpy())
    print('prediction: {}'.format(ix_to_label[pred]))
    print('actual: {}'.format(label))
    if label==ix_to_label[pred]:
      correct_count+=1
    total_count+=1

--- AFTER TRAINING ---
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[9.9991e-01, 8.5448e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[9.9991e-01, 8.5448e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[9.9991e-01, 8.5448e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[8.7341e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


tensor([[9.9991e-01, 8.5448e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[9.9991e-01, 8.5448e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[9.9991e-01, 8.5451e-05]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 0
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 0
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>)
prediction: 1
actual: 1
tensor([[8.7336e-05, 9.9991e-01]], device='cuda:0', grad_fn=<SoftmaxBackw

In [40]:
print (correct_count/total_count)

0.8078


In [0]:
torch.save(bow,'model.json')

from google.colab import files
files.download("model.json")

In [0]:
from google.colab import files
temp_test = files.upload()


In [0]:
torch.load(io.BytesIO(temp_test['model.json']))